name: New Release

on:
  milestone:
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Project Version
        id: get_version
        uses: mod-posh/GetProjectVersion@v0.0.2.2
        with:
          Filename: 'TerraformRegistryClient\TerraformRegistryClient.csproj'
          verbose: "verbose"

      - name: Create Release Notes
        uses: mod-posh/Issue2ReleaseNotes@v0.0.3.3
        with:
          milestone_number: ${{ github.event.milestone.number }}
          verbose: 'verbose'
          github_token: ${{ secrets.PAT }}

      - name: Pull Latest Changes
        run: git pull origin ${{ github.ref_name }}
        shell: bash

      - name: Create Release
        uses: mod-posh/NewTaggedRelease@v0.0.3.2
        with:
          name: 'Release v${{ env.VERSION }}'
          filename: 'RELEASE.md'
          version: ${{ env.VERSION }}
          verbose: 'verbose'
          github_token: ${{ secrets.PAT }}

      - name: Run markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
          fix: true